#!/usr/bin/env php
<?php

$files = scandir(__DIR__);

$manifest = array();

foreach ($files as $file) {
	if (substr($file, 0, 5) === 'give-') {
		$sha1 = sha1_file($file);
		preg_match('/give-([0-9\.]*).phar/', $file, $match);
		$manifest[] = array(
			'name' => 'give.phar',
			'sha1' => $sha1,
			'url' => 'https://raw.github.com/mneuhaus/Give-Repository/master/' . $file,
			'version' => $match[1]
		);
	}
}

file_put_contents('manifest.json', json_encode($manifest));

?>